# Generated by Django 4.2.8 on 2024-01-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0496_alter_scheduledmessage_read_by_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="isBoard",
            field=models.BooleanField(default=False),
        ),
    ]
