# Generated by Django 4.2.8 on 2024-01-22 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0497_stream_isboard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stream",
            old_name="isBoard",
            new_name="is_board",
        ),
    ]
